version: "3"

services:
  app:
    container_name: foocho-app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5252:5252"
    command: sh -c "python3 /app/db.py && python3 /app/app.py"